BEGIN TRANSACTION;
PRAGMA foreign_keys = OFF;

-- Переименовываем старую таблицу
ALTER TABLE MASA RENAME TO MASA_OLD;

-- Создаём новую таблицу с правильным референсом
CREATE TABLE IF NOT EXISTS "MASA" (
	"ID"	INTEGER,
	"ZODIACID"	INTEGER,
	"SHUNYANAKSHATRA"	TEXT,
	"SHUNYATITHI"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("ZODIACID") REFERENCES "ZODIAC"("ID")
);

-- Переносим все данные
INSERT INTO MASA (ID, ZODIACID, SHUNYANAKSHATRA, SHUNYATITHI)
SELECT ID, ZODIAKID, SHUNYANAKSHATRA, SHUNYATITHI
FROM MASA_OLD;

-- Удаляем старую таблицу
DROP TABLE MASA_OLD;

PRAGMA foreign_keys = ON;
COMMIT;
